### PR TITLE
Added .env Functionality To Project

### PR DESCRIPTION
**Pull request by jabarihunt**
Implemented .env functionality.  I used the vlucas/phpdotenv library to do this, which required the addition of Composer to the project.

### CODE REVIEW

**Comment by SieciechPL** [comment]
Good job, I like your changes. 
This project needs a routing and spliting html and php to separated files. Also layers like controler, service, model and view are needed and I think you will able to do that :)

**Comment by Mekaboo** [comment]
Hey @SieciechPL !!!

Question for ya...why would I need an MVC format for this? Ive dealt with MVC frameworks in the past like Codeigniter and Laravel and tried to stay clear of those for this project.

**Comment by SieciechPL** [comment]
It no necessarly have to be a MVC, but it is a good pattern. I am talking about organize the code. Few issues with current code organize that I found in a couple of minutes:
- addEdit.php - What I can add or edit here? With REST url convinient it will be /games/add and /games/1/edit and it is oblivious what it does
- you are store the php and html in the same file, hopefully you place logic part before the view part, but you repeat the same code everywhere, move the html code to dedicated files in decicated directory then you will be able to extract code that you repeat many times (html header and footer for example) to dedicated file and include that file where is needed. Now no one will use you script, because it will be hard to customize it and keep it up to date, because the customization will makes a lot of conflicts with current codebase.
- now you need to manually include necessarly files like db class, user model, etc. When you configure your namespace in omposer.json then you will be able to forgot about includings because the autoloader will include files when (and only when) will be necessary. And also the IDE with intelisense will show you that the class is used in that file, so you will be able to remove the use keyword if the class if no more necessary in the file, that it will be hard to maintain with include keyword
- you should avoid to making the root path of the project as public, because you may want to implement functionallity for buying games and you will need store invoices somewhere and now when all can see the source of this project then can try to get invoice files with making many request and in some attemps may success so it is dangerous
- additionally you shouldn't use .php in the url, use pretty url with url rewrite to hide the technology that support the project for security reason and also it is looks old school :)
- sometime you use a camelCase, sometimes kebab-case, you should choose one case for file, one case for classes and methods and don't change if for being consistent and you make a mess in you code and it make you slow down.
I know that you want to implement new functionallity fast, but the quality of the architecture is also important and every time when you forget about the architecture then you will implement new functionallity slower because of some code issues

**Comment by jabarihunt** [comment]
@Mekaboo - I concur with @SieciechPL's comments.  I know it may seem a little confusing now, but I promise you as the project grows you will greatly appreciate the code organization he's suggesting!

A single example is moving repeated code to its own template, such as the header and footer.  Imagine having 40 pages/views on the website, then you need to add a link to the header and footer.  That is a change that must happen in 40 different files (in two different places), verses having a single header and footer that is included into each view.  Then you'd only have to make the change once in the header and footer.

Each of those points mentioned in the comment above should be added in the project's [Issues](https://github.com/Mekaboo/Swarzie/issues) section individually.  That way they can be tackled with separate pull requests.  It also makes it easy to prioritize issues, as doing some tasks before others will be easier than the other way around.  In addition to that list, I'd add Dockerizing the project (though, that is a new feature more so than code organization).

**Comment by Mekaboo** [comment]
I get both of yall!! As I skim through it I do notice there are alot of files and things can be condensed. Thank yall for the insight..it means lot!!!

**Pull request merged**
